/* Autogenerated by png2wx.pl on Sun Jul 12 13:26:15 2020 */
#ifndef AISICON_H
#define AISICON_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_aisicon;

#endif /* AISICON_H */
