/* Autogenerated by png2wx.pl on Sun Jul 12 10:27:05 2020 */
#ifndef AISRADAR_H
#define AISRADAR_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_aisradar;

#endif /* AISRADAR_H */
