/* Autogenerated by png2wx.pl on Fri Jul 17 12:14:25 2020 */
#ifndef AISVIEW_H
#define AISVIEW_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_aisview;

#endif /* AISVIEW_H */
