/* Autogenerated by png2wx.pl on Fri Jul 17 12:28:10 2020 */
#ifndef TARGET_ALARM_H
#define TARGET_ALARM_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_target_alarm;

#endif /* TARGET_ALARM_H */
