/* Autogenerated by png2wx.pl on Fri Jul 17 12:27:48 2020 */
#ifndef TARGET_UNK_H
#define TARGET_UNK_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_target_unk;

#endif /* TARGET_UNK_H */
