/* Autogenerated by png2wx.pl on Fri Jul 17 12:26:34 2020 */
#ifndef YACHT_H
#define YACHT_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_yacht;

#endif /* YACHT_H */
