/* Autogenerated by png2wx.pl on Fri Jul 17 12:25:40 2020 */
#ifndef YACHT_UNK_H
#define YACHT_UNK_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_yacht_unk;

#endif /* YACHT_UNK_H */
